log:
  level: DEBUG
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    # Only considers containers with traefik.enable=true
    exposedByDefault: false
api:
  dashboard: true
  insecure: true
entrypoints:
  web: 
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure: 
    address: :443
    tls: {}
certificatesresolvers:
  cloudflare:
    acme:
      email: jonathanheromin@gmail.com
      storage: /var/traefik/certs/cloudflare-acme.json
      caServer: 'https://acme-v02.api.letsencrypt.org/directory'
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
